language: go

go:
  - "1.13.4"

stages:
  - build

install: go get -v github.com/spf13/hugo

script:
  # 安装主题
  #- git clone https://github.com/kakawait/hugo-tranquilpeak-theme.git
  # 运行hugo命令
  - hugo

env:
 global:
   # Github Pages
   - GH_REF: https://github.com/gy0624ww/hugo_blog.git

deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip-cleanup: true # 重要，不能省略
  local-dir: public # 静态站点文件所在目录
  # target-branch: master # 要将静态站点文件发布到哪个分支
  github-token: $GITHUB_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  # fqdn:  # 如果是自定义域名，此处要填
  keep-history: true # 是否保持target-branch分支的提交记录
  on:
    branch: master # 博客源码的分支
  repo: gy0624ww/gy0624ww.github.io
  target_branch: master
  email: gy0624ww@foxmail.com
  name: guanyue

